language: python

python:
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq doxygen

script:
    - tests/unit/tests.py
    - tests/functional/tests.py
