language: python

python:
    - "3.4"
    - "3.5"
    - "3.6"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq doxygen

install:
    - pip install -r dev-requirements.txt
    - pip install coveralls

script:
    - flake8
    - ./setup.py sdist --formats=bztar
    - tar xf dist/doxyqml-*.tar.bz2
    - cd doxyqml-*
    - ./setup.py install
    - tests/run-coverage
    # Run functional tests again, but running Doxyqml as a separate process
    # instead of as a Python module
    - tests/functional/tests.py

after_success:
    coveralls
